# theme basic info
theme_info:
  name: ILS
  version: 2.0.1
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# favicon
favicon: /images/favicon.svg

# avatar
avatar: /images/avatar.jpeg

# navigation menu
menu:
  主页: /
  Archives: /archives
  About: /about
  # ...

# RSS
rss:
  enable: true

# comment plugin
comments:
  # Valine https://github.com/xCss/Valine
  valine:
    enable: false
    appid:                # your leancloud application appid
    appkey:               # your leancloud application appkey
    meta:                 # comment input meta, type: Array, values: ['nick','mail','link']
    placeholder:          # your placeholder

  # Gitalk https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    github_id: chazyu1996            # GitHub repo owner
    repository: chazyu1996.github.io         # Repository name to store issues
    client_id: c2072d06f1a2f2c5d6f2            # GitHub Application Client ID
    client_secret: 429efb33ae5e4f3157ed2bb9a0c0028c9f7d71c3        # GitHub Application Client Secret

# website count
website_count:
  # busuanzi http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  unescape: false

  # Preload the search data when the page loads.
  preload: true

# Post word count
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  wordcount: false  # word count, one article
  min2read: false   # time to read, one article

# Home page article block display settings
home_article:
  category: true # show category in article block
  tag: true # show tags in article block
  tag_limit: 10 # max number of tags shown in article block

# Code Copy
code_copy:
  enable: true
  style: mac # values: default | flat | mac

# sidebar tools
side_tools:
  enable: true
  position: right  # values: left | right

# back to top
back2top:
  enable: true
  position: right  # values: left | right

# Table of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

# magic theme
magic:
  enable: true
  scale: true 
  shadow: false
