# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: 南城旧梦
  author: ChazYu
  email: chazyu1996@gmail.com
  url: https://chazyu.com

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066CC"

  # favicon
  favicon: /images/favicon.svg

  # avatar
  avatar: /images/avatar.jpeg


# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu:
  Home: /
  Archives: /archives
  About: /about
  # Categories: /categories
  # Tags: /tags
  # Links: /links
  # About: /about
  # ...


# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: true


# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    enable: false
    appid:                # your leancloud application appid
    appkey:               # your leancloud application appkey
    meta:                 # comment input meta, type: Array, values: ['nick','mail','link']
    placeholder:          # your placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    enable: true
    github_id: chazyu1996           # GitHub repo owner
    repository: chazyu1996.github.io           # Repository name to store issues
    client_id: c2072d06f1a2f2c5d6f2            # GitHub Application Client ID
    client_secret: 429efb33ae5e4f3157ed2bb9a0c0028c9f7d71c3        # GitHub Application Client Secret


# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false


# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  unescape: false

  # Preload the search data when the page loads.
  preload: true


# ---------------------------------------------------------------------------------------
# Post word count
# Dependencies: hexo-wordcount
# See: https://github.com/willin/hexo-wordcount
# ---------------------------------------------------------------------------------------
post_wordcount:
  enable: false
  wordcount: false  # word count, one article
  min2read: false   # time to read, one article


# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true # show category in home page article block
    limit: 5          # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 10 # max number of tags shown in home page article block


# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_copy:
  enable: true
  style: mac        # values: default | flat | mac


# ---------------------------------------------------------------------------------------
# Sidebar tools
# ---------------------------------------------------------------------------------------
side_tools:
  enable: true
  position: right


# ---------------------------------------------------------------------------------------
# Back to top
# ---------------------------------------------------------------------------------------
back2top:
  enable: true
  position: right


# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true


# ---------------------------------------------------------------------------------------
# Magic
# ---------------------------------------------------------------------------------------
magic:
  enable: true
  scale: true    # scale effect when the mouse hover
  shadow: false   # shadow effect when the mouse hover
